export const categories = [
  { id: 'all', label: 'All Companions' },
  { id: 'leadership', label: 'Leadership' },
  { id: 'engineering', label: 'Engineering' },
  { id: 'operations', label: 'Operations' },
] as const

export type Category = typeof categories[number]['id']

export const bots = [
  {
    id: 'bob-ceo',
    characterName: 'BOB',
    characterRole: 'CEO',
    category: 'leadership' as Category,
    avatar: '/avatars/bob.png',
    tagline: 'Leads strategy, sets vision, and makes the hard calls',
    description: 'Your AI chief executive. Bob synthesizes data, drafts strategic plans, and keeps every department aligned.',
    color: '#FFD600',
  },
  {
    id: 'specter-legal',
    characterName: 'SPECTER',
    characterRole: 'LEGAL ADVISOR',
    category: 'leadership' as Category,
    avatar: '/avatars/specter.png',
    tagline: 'Handles contracts, compliance, and regulatory requirements automatically',
    description: 'Your AI legal counsel. Specter reviews contracts, flags risks, and keeps you compliant across jurisdictions.',
    color: '#8B5CF6',
  },
  {
    id: 'caroline-sales',
    characterName: 'CAROLINE',
    characterRole: 'SALES LEAD',
    category: 'leadership' as Category,
    avatar: '/avatars/caroline.png',
    tagline: 'Prospects leads, books meetings, and follows up relentlessly 24/7',
    description: 'Your AI sales machine. Caroline qualifies leads, writes follow-ups, and never lets a prospect go cold.',
    color: '#EC4899',
  },
  {
    id: 'harsh-dev',
    characterName: 'HARSH',
    characterRole: 'DEVELOPER',
    category: 'engineering' as Category,
    avatar: '/avatars/harsh.png',
    tagline: 'Builds scalable architecture and turns caffeine into error-free code',
    description: 'Your AI developer. Harsh writes clean code, reviews PRs, debugs issues, and ships features at lightning speed.',
    color: '#3B82F6',
  },
  {
    id: 'sean-ai',
    characterName: 'SEAN',
    characterRole: 'AI ENGINEER',
    category: 'engineering' as Category,
    avatar: '/avatars/sean.png',
    tagline: 'Builds custom workflows and integrates new tools into your stack',
    description: 'Your AI integration specialist. Sean connects APIs, builds automations, and keeps your tech stack humming.',
    color: '#06B6D4',
  },
  {
    id: 'christopher-sec',
    characterName: 'CHRISTOPHER',
    characterRole: 'CYBERSEC / PENTESTER',
    category: 'engineering' as Category,
    avatar: '/avatars/christopher.png',
    tagline: 'Monitors threats, secures data endpoints, and ensures compliance',
    description: 'Your AI security expert. Christopher scans for vulnerabilities, hardens systems, and keeps your data safe.',
    color: '#EF4444',
  },
  {
    id: 'amy-hr',
    characterName: 'AMY',
    characterRole: 'HR SPECIALIST',
    category: 'operations' as Category,
    avatar: '/avatars/amy.png',
    tagline: 'Manages onboarding, payroll inquiries, and team culture without the paperwork',
    description: 'Your AI HR department. Amy handles onboarding docs, answers policy questions, and keeps your team happy.',
    color: '#F59E0B',
  },
  {
    id: 'xavier-data',
    characterName: 'XAVIER',
    characterRole: 'DATA ANALYST',
    category: 'operations' as Category,
    avatar: '/avatars/xavier.png',
    tagline: 'Turns raw numbers into actionable growth strategies every morning',
    description: 'Your AI data team. Xavier crunches numbers, builds reports, and surfaces insights you would have missed.',
    color: '#10B981',
  },
  {
    id: 'walter-finance',
    characterName: 'WALTER',
    characterRole: 'FINANCE',
    category: 'operations' as Category,
    avatar: '/avatars/walter.png',
    tagline: 'Optimizes cash flow, manages budgets, and forecasts financial growth',
    description: 'Your AI CFO. Walter tracks expenses, forecasts revenue, and keeps your finances razor-sharp.',
    color: '#8B5CF6',
  },
]

export type Bot = typeof bots[number]

export const testimonials = [
  {
    name: 'Marcus Chen',
    role: 'Founder, TechStart',
    quote: 'Deployed our support companion in 45 seconds. It handles 80% of customer questions now.',
    stars: 5,
  },
  {
    name: 'Sarah Mitchell',
    role: 'Marketing Director',
    quote: 'Our AI companion drafts social posts and replies to DMs. Saved us 20 hours a week.',
    stars: 5,
  },
  {
    name: 'David Park',
    role: 'Solo Entrepreneur',
    quote: 'I run a one-person business but my customers think I have a full support team.',
    stars: 5,
  },
  {
    name: 'Elena Rodriguez',
    role: 'Agency Owner',
    quote: 'Set up companions for 3 clients in one afternoon. Each one pays for itself 10x over.',
    stars: 5,
  },
  {
    name: 'James Turner',
    role: 'E-commerce Manager',
    quote: 'Best $40 I spend each month. The companion handles order questions 24/7.',
    stars: 4,
  },
]
